/**
 * CCAGI SDK Phase 6: Documentation Command Handlers
 *
 * Based on SDK_REQUIREMENTS.md v6.19.0
 * Commands: CMD-018 to CMD-021 (User Manual, Demo, Test Accounts, Test Data)
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { BaseCommandHandler } from '../base';
import { registerCommand } from '../registry';
import type {
  CommandContext,
  CommandHandlerResult,
} from '../types';

// =============================================================================
// CMD-018: Generate User Manual
// =============================================================================

export class GenerateUserManualHandler extends BaseCommandHandler<{
  manualPath: string;
  sections: number;
}> {
  constructor() {
    super('CMD-018', '/generate-user-manual');
  }

  protected async executeInternal(
    context: CommandContext
  ): Promise<CommandHandlerResult<{ manualPath: string; sections: number }>> {
    const outputPath = this.resolveOutputPath(context);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    const manual = this.generateUserManual();
    const manualPath = path.join(path.dirname(outputPath), 'USER_MANUAL.md');
    await fs.writeFile(manualPath, manual, 'utf-8');

    const sections = (manual.match(/^## /gm) || []).length;

    context.logger.info(`User manual generated: ${manualPath} (${sections} sections)`);

    return this.success(
      { manualPath, sections },
      [manualPath],
      [
        {
          type: 'documentation',
          url: manualPath,
          description: 'User Manual',
        },
      ]
    );
  }

  private generateUserManual(): string {
    return `# User Manual

## Table of Contents
1. [Introduction](#introduction)
2. [Getting Started](#getting-started)
3. [Features](#features)
4. [User Guide](#user-guide)
5. [FAQ](#faq)
6. [Troubleshooting](#troubleshooting)

---

## Introduction
Welcome to the application user manual. This guide will help you understand and use all features effectively.

### System Requirements
- Modern web browser (Chrome, Firefox, Safari, Edge)
- Stable internet connection
- Screen resolution: 1024x768 minimum

---

## Getting Started

### Creating an Account
1. Navigate to the registration page
2. Enter your email and password
3. Verify your email
4. Complete your profile

### Logging In
1. Go to the login page
2. Enter your credentials
3. Click "Sign In"

### Dashboard Overview
The dashboard provides an overview of your activity and quick access to main features.

---

## Features

### Feature 1: Data Management
- Create, read, update, and delete records
- Bulk import/export functionality
- Search and filter capabilities

### Feature 2: Reporting
- Generate reports
- Export to PDF/CSV
- Schedule automated reports

### Feature 3: Settings
- Profile settings
- Notification preferences
- Security settings

---

## User Guide

### Navigation
- Use the sidebar for main navigation
- Breadcrumbs show your current location
- Quick actions in the header

### Data Entry
- Required fields are marked with *
- Validation errors appear inline
- Auto-save is enabled by default

### Keyboard Shortcuts
| Shortcut | Action |
|----------|--------|
| Ctrl+S | Save |
| Ctrl+N | New |
| Esc | Cancel |

---

## FAQ

### How do I reset my password?
Click "Forgot Password" on the login page and follow the instructions.

### How do I export my data?
Go to Settings > Export and select your preferred format.

### Is my data secure?
Yes, all data is encrypted in transit and at rest.

---

## Troubleshooting

### Common Issues

#### Page not loading
- Check your internet connection
- Clear browser cache
- Try a different browser

#### Login issues
- Verify your email is correct
- Reset your password
- Contact support if issues persist

### Contact Support
- Email: support@example.com
- Phone: 1-800-EXAMPLE
- Hours: Mon-Fri 9AM-5PM EST

---
*Generated by CCAGI SDK v6.19.0*
`;
  }

  canParallelize(): boolean {
    return true;
  }
}

// =============================================================================
// CMD-019: Generate Demo Scenario
// =============================================================================

export class GenerateDemoScenarioHandler extends BaseCommandHandler<{
  demoPath: string;
  steps: number;
}> {
  constructor() {
    super('CMD-019', '/generate-demo-scenario');
  }

  protected async executeInternal(
    context: CommandContext
  ): Promise<CommandHandlerResult<{ demoPath: string; steps: number }>> {
    const outputPath = this.resolveOutputPath(context);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    const demo = this.generateDemoScenario();
    const demoPath = path.join(path.dirname(outputPath), 'DEMO_SCENARIO.md');
    await fs.writeFile(demoPath, demo, 'utf-8');

    const steps = (demo.match(/^### Step/gm) || []).length;

    context.logger.info(`Demo scenario generated: ${demoPath} (${steps} steps)`);

    return this.success({ demoPath, steps }, [demoPath]);
  }

  private generateDemoScenario(): string {
    return `# Demo Scenario

## Overview
This document provides a step-by-step demonstration of the application's key features.

**Duration**: 15 minutes
**Audience**: Stakeholders, potential users, sales team

---

## Prerequisites
- Demo account credentials
- Sample data loaded
- Stable internet connection

---

## Demo Flow

### Step 1: Login and Dashboard (2 min)
1. Navigate to the login page
2. Enter demo credentials
3. Show the dashboard overview
4. Highlight key metrics and widgets

**Talking Points**:
- "Notice how the dashboard gives you an instant overview..."
- "Key metrics are prominently displayed..."

### Step 2: Create New Record (3 min)
1. Click "New" button
2. Fill in the form fields
3. Show validation in action
4. Save and confirm creation

**Talking Points**:
- "Creating new records is intuitive..."
- "Real-time validation helps prevent errors..."

### Step 3: Search and Filter (2 min)
1. Use the search bar
2. Apply filters
3. Show results updating in real-time

**Talking Points**:
- "Find what you need instantly..."
- "Powerful filtering options..."

### Step 4: Edit and Update (2 min)
1. Select a record
2. Make changes
3. Save and show confirmation

**Talking Points**:
- "Changes are tracked automatically..."
- "Audit trail for compliance..."

### Step 5: Generate Report (3 min)
1. Navigate to Reports
2. Select report type
3. Configure parameters
4. Generate and preview
5. Export to PDF

**Talking Points**:
- "Comprehensive reporting capabilities..."
- "Export in multiple formats..."

### Step 6: Settings and Customization (2 min)
1. Show profile settings
2. Demonstrate customization options
3. Show notification preferences

**Talking Points**:
- "Fully customizable to your needs..."
- "Control exactly how you want to be notified..."

### Step 7: Q&A (1 min)
- Open floor for questions
- Address common concerns

---

## Backup Scenarios

### If login fails:
Use the offline demo mode

### If data doesn't load:
Show pre-prepared screenshots

### If internet is slow:
Use local development environment

---

## Demo Accounts

| Role | Email | Password |
|------|-------|----------|
| Admin | demo-admin@example.com | DemoPass123! |
| User | demo-user@example.com | DemoPass123! |

---
*Generated by CCAGI SDK v6.19.0*
`;
  }

  canParallelize(): boolean {
    return true;
  }
}

// =============================================================================
// CMD-020: Generate Test Accounts
// =============================================================================

export class GenerateTestAccountsHandler extends BaseCommandHandler<{
  accountsPath: string;
  accountsCreated: number;
}> {
  constructor() {
    super('CMD-020', '/generate-test-accounts');
  }

  protected async executeInternal(
    context: CommandContext
  ): Promise<CommandHandlerResult<{ accountsPath: string; accountsCreated: number }>> {
    const outputPath = this.resolveOutputPath(context);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });

    const accounts = this.generateTestAccounts();
    const accountsPath = path.join(path.dirname(outputPath), 'test-accounts.json');
    await fs.writeFile(accountsPath, JSON.stringify(accounts, null, 2), 'utf-8');

    context.logger.info(`Test accounts generated: ${accountsPath}`);

    return this.success(
      { accountsPath, accountsCreated: accounts.length },
      [accountsPath]
    );
  }

  private generateTestAccounts() {
    return [
      {
        id: 'test-admin-001',
        email: 'admin@test.local',
        password: 'TestAdmin123!',
        role: 'admin',
        name: 'Test Admin',
        permissions: ['read', 'write', 'delete', 'admin'],
      },
      {
        id: 'test-user-001',
        email: 'user1@test.local',
        password: 'TestUser123!',
        role: 'user',
        name: 'Test User 1',
        permissions: ['read', 'write'],
      },
      {
        id: 'test-user-002',
        email: 'user2@test.local',
        password: 'TestUser123!',
        role: 'user',
        name: 'Test User 2',
        permissions: ['read', 'write'],
      },
      {
        id: 'test-viewer-001',
        email: 'viewer@test.local',
        password: 'TestViewer123!',
        role: 'viewer',
        name: 'Test Viewer',
        permissions: ['read'],
      },
      {
        id: 'test-api-001',
        email: 'api@test.local',
        password: 'TestAPI123!',
        role: 'api',
        name: 'API Test Account',
        apiKey: 'test_api_key_12345',
        permissions: ['read', 'write'],
      },
    ];
  }

  canParallelize(): boolean {
    return true;
  }
}

// =============================================================================
// CMD-021: Generate Test Data
// =============================================================================

export class GenerateTestDataHandler extends BaseCommandHandler<{
  fixturesPath: string;
  seedsPath: string;
  recordsGenerated: number;
}> {
  constructor() {
    super('CMD-021', '/generate-test-data');
  }

  protected async executeInternal(
    context: CommandContext
  ): Promise<CommandHandlerResult<{
    fixturesPath: string;
    seedsPath: string;
    recordsGenerated: number;
  }>> {
    const outputPaths = this.resolveOutputPath(context).split(', ');
    const fixturesDir = outputPaths[0] || `${context.projectRoot}/tests/fixtures`;
    const seedsDir = outputPaths[1] || `${context.projectRoot}/tests/seeds`;

    await fs.mkdir(fixturesDir, { recursive: true });
    await fs.mkdir(seedsDir, { recursive: true });

    // Generate fixtures
    const fixtures = this.generateFixtures();
    const fixturesPath = path.join(fixturesDir, 'data.json');
    await fs.writeFile(fixturesPath, JSON.stringify(fixtures, null, 2), 'utf-8');

    // Generate seeds
    const seeds = this.generateSeeds();
    const seedsPath = path.join(seedsDir, 'seed.sql');
    await fs.writeFile(seedsPath, seeds, 'utf-8');

    const recordsGenerated = fixtures.users.length + fixtures.items.length;

    context.logger.info(`Test data generated: ${recordsGenerated} records`);

    return this.success(
      { fixturesPath, seedsPath, recordsGenerated },
      [fixturesPath, seedsPath]
    );
  }

  private generateFixtures() {
    return {
      users: [
        { id: 1, name: 'John Doe', email: 'john@example.com', role: 'admin' },
        { id: 2, name: 'Jane Smith', email: 'jane@example.com', role: 'user' },
        { id: 3, name: 'Bob Wilson', email: 'bob@example.com', role: 'user' },
      ],
      items: [
        { id: 1, name: 'Item 1', description: 'First test item', userId: 1 },
        { id: 2, name: 'Item 2', description: 'Second test item', userId: 2 },
        { id: 3, name: 'Item 3', description: 'Third test item', userId: 1 },
        { id: 4, name: 'Item 4', description: 'Fourth test item', userId: 3 },
      ],
      categories: [
        { id: 1, name: 'Category A' },
        { id: 2, name: 'Category B' },
      ],
    };
  }

  private generateSeeds(): string {
    return `-- Database Seeds
-- Generated by CCAGI SDK v6.19.0

-- Users
INSERT INTO users (id, name, email, role, created_at) VALUES
  (1, 'John Doe', 'john@example.com', 'admin', NOW()),
  (2, 'Jane Smith', 'jane@example.com', 'user', NOW()),
  (3, 'Bob Wilson', 'bob@example.com', 'user', NOW());

-- Categories
INSERT INTO categories (id, name, created_at) VALUES
  (1, 'Category A', NOW()),
  (2, 'Category B', NOW());

-- Items
INSERT INTO items (id, name, description, user_id, category_id, created_at) VALUES
  (1, 'Item 1', 'First test item', 1, 1, NOW()),
  (2, 'Item 2', 'Second test item', 2, 1, NOW()),
  (3, 'Item 3', 'Third test item', 1, 2, NOW()),
  (4, 'Item 4', 'Fourth test item', 3, 2, NOW());
`;
  }

  canParallelize(): boolean {
    return true;
  }
}

// =============================================================================
// Registration
// =============================================================================

export function registerPhase6Handlers(): void {

  registerCommand(new GenerateUserManualHandler());
  registerCommand(new GenerateDemoScenarioHandler());
  registerCommand(new GenerateTestAccountsHandler());
  registerCommand(new GenerateTestDataHandler());
}

export function getPhase6Handlers(): BaseCommandHandler[] {
  return [
    new GenerateUserManualHandler(),
    new GenerateDemoScenarioHandler(),
    new GenerateTestAccountsHandler(),
    new GenerateTestDataHandler(),
  ];
}
